# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'APITest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for APITest
  pod 'Then'
  pod 'lottie-ios'
  pod 'Alamofire', '~> 5.4'
  pod 'NMapsMap'
  pod 'PanModal'
  pod 'KakaoSDKAuth'  
  pod 'KakaoSDKUser'
end
