# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExhibitionApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExhibitionApp
  pod 'SnapKit', '~> 5.0.0'
  pod 'Then'
  pod 'Kingfisher', '~> 7.0'
  pod 'lottie-ios'
  pod 'Alamofire', '~> 5.4'
  pod 'CollectionViewPagingLayout'
  
end
